# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Sonar Scan
      # You may pin to the exact commit or the version.
      # uses: sijomc/sonarscan-action@5a3a0c0eacbe76ac7c3e3513696f7449f4f914a5
      uses: sijomc/sonarscan-action@1.1
      with:
        # SonarQube server URL
        host: http://127.0.0.1:9000/
        # The project's unique key. Allowed characters are: letters, numbers, -, _, . and :, with at least one non-digit.
        projectKey: demo-c-sharp
        # Name of the project that will be displayed on the web interface.
        projectName: demo-c-sharp

